# Generated by Django 4.2.5 on 2023-09-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Врач',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Пациент',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField()),
                ('SEX', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Пожелания_пациентов',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spciality_врача', models.CharField(max_length=50)),
                ('Wish', models.TextField()),
                ('ID_пациента', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.пациент')),
            ],
        ),
        migrations.CreateModel(
            name='Записи_пациентов_к_врачам',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_записи', models.DateField()),
                ('ID_врача', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.врач')),
                ('ID_пациента', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.пациент')),
            ],
        ),
    ]
